name: PNPM Lint and Compile

on:
  workflow_call:

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 2
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .node-version
          check-latest: false
          cache: pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
        with:
          version: 11.7.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --config.strict-dep-builds=false --config.dangerously-allow-all-builds=true
      - name: Lint code
        run: pnpm --config.verify-deps-before-run=false --config.strict-dep-builds=false run lint

  compile:
    needs: lint
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 2
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .node-version
          check-latest: false
          cache: pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
        with:
          version: 11.7.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --config.strict-dep-builds=false --config.dangerously-allow-all-builds=true
      - name: Compile code
        run: pnpm --config.verify-deps-before-run=false --config.strict-dep-builds=false run build && rm -rf dist
      - name: Cleanup
        uses: atos-actions/clean-self-hosted-runner@c6ce136031329a4435508e02b3f97fd85353f744 # v1
        if: ${{ always() }}
